### ISSUE TITLE
Not accessible maven repository

### ISSUE THREAD

**Issue by jakuub** [link-nv/eu-vat-check#1]
Hello, I want to ask, if your maven will be available again. We have this library as an dependency in our project and it stops compiling last time we try to deploy it, as it can't contact your maven repository. 

If you have a time to reply, we only need to know, if we need to replace this depencency, or it will be accessible later. 

Thanks a lot, 

Jakub

**Comment by wvdhaute** [comment]
Hello jakuub,

Our maven repository has recently been moved and not all artifacts were yet moved
The 0.4 release has been moved so you should be able to build again.

Kind regards,
Wim.

**Comment by jakuub** [comment]
Thank you for your response, 

Maybe I only don't understand something, but whe I access http://repo.linkid.be/releases/net/lin-k/eu/eu-vat-check/eu-vat-check-client/0.4 i get 
![image](https://cloud.githubusercontent.com/assets/1863153/16298003/8a048966-3933-11e6-87ae-fd0da33e1dfa.png)
And the build also failed.

**Comment by wvdhaute** [comment]
Hey jakuub,

Our new maven repository is no longer browsable.
But the artifacts are there. 

The artifacts where deployed to a wrong location tho, my bad, I have fixed this now.

For example see: 
http://repo.linkid.be/releases/net/lin-k/eu/eu-vat-check/eu-vat-check-client/0.4/eu-vat-check-client-0.4.jar

kind regards,
Wim.

**Comment by jakuub** [comment]
Hello Wim, 

thank you very much, our build finally passed.

regards,
Jakuub

**Comment by jakuub** [comment]
Hello Wim, 

now again we can't connect to the repository. Even direct link you shared before don't work now. 

Sorry if you already working on it or have multiple issues like this, I didn't want to overload you.

Kind regards, 
Jakuub

**Comment by dhouthoo** [comment]
That repository is down forever.

**Comment by jakuub** [comment]
Can I ask, if this library will be accessible anywhere, or should we replace it by something else?

**Comment by dhouthoo** [comment]
I just committed a fix that should make it build again without the repo. At least the tests pass. Probably the nice thing to do is to figure out where releases of this project can be pushed to.

**Comment by jakuub** [comment]
Ok, so if I get it correctly, the solution for us is to not use your repository, but build it by ourselfes and use it without using maven?

**Comment by dhouthoo** [comment]
For now, build it yourself and install it in your local repo, or on your
internal company repo. You can then use this library with maven.

**Comment by jakuub** [comment]
Ok, thank you for information :-). We will use it directly :-).
